# Generated by Django 3.2.21 on 2023-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='release_date',
            field=models.CharField(max_length=5),
        ),
    ]
