# Generated by Django 3.2.21 on 2023-09-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0002_alter_informations_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informations',
            options={'verbose_name': 'Information'},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'Page'},
        ),
    ]
