# Generated by Django 3.2.21 on 2023-09-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0003_auto_20230929_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='name',
        ),
    ]
