# Generated by Django 3.2.22 on 2023-10-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0005_auto_20231006_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
