# Generated by Django 3.2.22 on 2023-10-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0007_remove_informations_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='manga_title',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
