# Generated by Django 3.2.23 on 2023-11-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0008_informations_manga_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
