# Generated by Django 3.2.23 on 2023-12-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0011_remove_pages_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
    ]
